### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by KumarShivam382**
Added a smooth horizontal rule and updated its style.css

### CODE REVIEW

**Review by harshit-paneri — COMMENTED** [review]
Please add screenshot of your changes also

**Comment by KumarShivam382** [comment]
image

**Comment by KumarShivam382** [comment]
Added please review.

**Comment by harshit-paneri** [comment]
Where is the map in the web image

**Comment by KumarShivam382** [comment]
It says waiting for map.googleapis.com

**Comment by KumarShivam382** [comment]
Please look at the left downward corner

**Comment by KumarShivam382** [comment]
Please look at left down corner.


IMG_20221015_115114

**Comment by KumarShivam382** [comment]
please review and also reply if you want me to do other changes.

**Comment by harshit-paneri** [comment]
Ok Let me work on it, then you send PR, Or if you want to do, there is google map in the web page look at code, or revert the code

**Pull request closed without merging**
